sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  global:
    - LIBGL_ALWAYS_SOFTWARE=1
    - VERBOSE_OUTPUT='false'
    - CATKIN_CONFIG='--no-install'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
    - AFTER_SCRIPT='sh $CATKIN_WORKSPACE/src/uuv_simulation_evaluation/.ci_config/run_tests.sh'
matrix:
  include:
    - env: USE_DEB=true ROS_DISTRO=kinetic ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true BEFORE_SCRIPT='sh $CATKIN_WORKSPACE/src/uuv_simulation_evaluation/.ci_config/ros_kinetic.sh'
    - env: USE_DEB=true ROS_DISTRO=lunar ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true BEFORE_SCRIPT='sh $CATKIN_WORKSPACE/src/uuv_simulation_evaluation/.ci_config/ros_lunar.sh'
  allow_failures:
    - env: USE_DEB=true ROS_DISTRO=lunar ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true BEFORE_SCRIPT='sh $CATKIN_WORKSPACE/src/uuv_simulation_evaluation/.ci_config/ros_lunar.sh'
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
